Mecanum Wheel Odometry in firmware_message_converter
LeoRover/leo_robot-ros2 pull request #5
Opened 2023-09-18 12:29 UTC by Bitterisland6

Added handling of "/firmware/wheel_odom_mecanum" topic in firmware message converter script

2023-09-20 13:08 UTC, bjsowa requested changes

2023-09-20 13:08 UTC, bjsowa commented on leo_bringup/config/firmware.yaml
This file does not belong to this PR, delete it

2023-09-20 13:08 UTC, bjsowa commented on leo_fw/src/firmware_message_converter.cpp
> +  bool wheel_odom_mecanum_advertised;
Use `_` prefix for private member variables

2023-09-27 16:29 UTC, Bitterisland6 commented on leo_bringup/config/firmware.yaml
Done

2023-09-27 16:30 UTC, Bitterisland6 commented on leo_fw/src/firmware_message_converter.cpp
> +  bool wheel_odom_mecanum_advertised;
Removed those flags as I switched to different solution

2023-10-16 15:00 UTC, bjsowa approved these changes

2023-10-16 15:00 UTC, merged